# Generated by Django 4.2.5 on 2023-11-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_recommend',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
