# Generated by Django 4.2.5 on 2023-11-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatting',
            name='content',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
