# Generated by Django 4.2.5 on 2023-11-21 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_chatting_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chatting',
        ),
    ]
