# Generated by Django 4.2.5 on 2023-11-26 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chattings', '0002_rename_users_chatting_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatting',
            old_name='content',
            new_name='message',
        ),
    ]
