# Generated by Django 4.2.5 on 2023-11-28 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comment_post_comment_user_commentlike_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='user',
        ),
        migrations.DeleteModel(
            name='CommentLike',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
